allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  core-js: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - pg-connection-string@2.14.0
  - pg-protocol@1.15.0
  - pg@8.22.0
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
