export const ACTIONS = [
  "access",
  "view",
  "create",
  "edit",
  "delete",
  "export",
  "suspend",
  "ban",
  "restore",
  "moderate",
  "status",
  "reply",
  "apply",
  "save",
  "send",
  "follow",
  "connect",
  "block",
  "react",
  "comment",
  "share",
  "vote",
] as const

export type ActionName = (typeof ACTIONS)[number]

export const ACTION_LABELS: Record<ActionName, string> = {
  access: "Truy cập",
  view: "Xem",
  create: "Tạo mới",
  edit: "Chỉnh sửa",
  delete: "Xóa",
  export: "Xuất dữ liệu",
  suspend: "Khóa tài khoản",
  ban: "Cấm",
  restore: "Khôi phục",
  moderate: "Duyệt / Kiểm duyệt",
  status: "Đổi trạng thái",
  reply: "Trả lời",
  apply: "Ứng tuyển",
  save: "Lưu",
  send: "Gửi",
  follow: "Theo dõi",
  connect: "Kết nối",
  block: "Chặn",
  react: "Tương tác",
  comment: "Bình luận",
  share: "Chia sẻ",
  vote: "Bình chọn",
}
