export const MODULES = [
  "admin",
  "dashboard",
  "feed",
  "network",
  "messages",
  "notifications",
  "profile",
  "cvs",
  "users",
  "companies",
  "jobs",
  "posts",
  "reports",
  "appeals",
  "audit",
  "contacts",
  "search",
  "brand",
  "report_types",
  "lookups",
  "settings",
  "roles",
] as const

export type ModuleName = (typeof MODULES)[number]

export const MODULE_LABELS: Record<ModuleName, string> = {
  admin: "Khu quản trị",
  dashboard: "Bảng điều khiển",
  feed: "Bảng tin",
  network: "Mạng lưới",
  messages: "Tin nhắn",
  notifications: "Thông báo",
  profile: "Hồ sơ",
  cvs: "CV",
  users: "Quản lý người dùng",
  companies: "Quản lý công ty",
  jobs: "Quản lý việc làm",
  posts: "Quản lý bài viết",
  reports: "Quản lý báo cáo",
  appeals: "Quản lý kháng nghị",
  audit: "Nhật ký hoạt động",
  contacts: "Liên hệ hỗ trợ",
  search: "Tìm kiếm",
  brand: "Thương hiệu",
  report_types: "Loại báo cáo",
  lookups: "Danh mục",
  settings: "Cài đặt hệ thống",
  roles: "Quản lý quyền",
}
